name: "Get latest release of repository"

description: "Get latest release including draft and prerelease. Return information about release"
inputs:
  myToken:
    description: "GitHub Token"
    required: true
  exclude_types:
    description: "Exclude release type (example: draft|prerelease)"
    required: false
  view_top:
    description: "View top releases to find release"
    required: false
    default: 100
outputs:
  id:
    description: 'Id of the release'
  name:
    description: 'Name of the release'
  tag_name:
    description: 'Tag of the release'
  created_at:
    description: 'Creation date of the release'
  draft:
    description: 'Release is draft'
  prerelease:
    description: 'Release is prerelease'
  release:
    description: 'Release is production release'
runs:
  using: "node18"
  main: "dist/index.js"
branding:
  icon: 'tag'
  color: 'purple'
